Julia 1.3:
  image: julia:1.3
  script: julia --project='@.' -e '
          using Pkg;
          Pkg.develop(PackageSpec(url="https://github.com/greimel/Literate.jl.git"));
          Pkg.build();
          Pkg.test(; coverage=true)'
  coverage: /Test Coverage (\d+\.\d+%)/
  after_script:
    - julia -e 'using Printf; using Pkg; Pkg.add("Coverage"); using Coverage; c, t = get_summary(process_folder()); @printf "Test Coverage %.2f%%\n" 100c/t'
pages:
  image: julia:1.3
  stage: deploy
  script:
    - julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.develop(PackageSpec(url="https://github.com/greimel/Literate.jl.git"));
          Pkg.develop(PackageSpec(url="https://github.com/greimel/LiterateWeave.jl.git"));
          Pkg.instantiate();
          include("docs/make.jl");'
    - mkdir -p public
    - mv docs/build public/dev
  artifacts:
    paths:
      - public
  only:
    - master
